# fly.toml app configuration file generated for closet-app-backend on 2023-08-25T13:23:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "closet-app-backend"
primary_region = "dfw"

[env]
    MONGODB_URI = "mongodb+srv://admin:0123456789@cluster0.rablf5o.mongodb.net/closet-app?retryWrites=true&w=majority"
    MONGODB_DB = "closet-app"
    ACCESS_TOKEN_SECRET = "ladybug-soccer"
    AWS_ACCESS_KEY_ID = "AKIAUOIQRDQKC2PN43P3"
    AWS_SECRET_ACCESS_KEY = "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"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[experimental]
  command = "node server.js"
