# fly.toml app configuration file for deploying a Node.js backend
# Adjust the settings as needed for your backend application

app = "closet-app"
primary_region = "mia"

[env]
  MONGODB_URI = "mongodb+srv://admin:0123456789@cluster0.rablf5o.mongodb.net/closet-app?retryWrites=true&w=majority"

  MONGODB_DB = "closet-app"

  ACCESS_TOKEN_SECRET = "ladybug-soccer"

  AWS_ACCESS_KEY_ID = "AKIAUOIQRDQKC2PN43P3"

  AWS_SECRET_ACCESS_KEY = "KDbGfjPDMX2qrP8go4SmInmMc//qR8tRIsxX5WjR"

[service]
  internal_port = 3000

[experimental]
  # Specify the command to start your Node.js server
  command = "node server.js"
  machine = "c-2x"
